#!/bin/bash
# Generate Firebase config files from environment variables
#
# Usage:
#   1. Create .env.local with your Firebase values (copy from .env.example)
#   2. Run: chmod +x scripts/generate-firebase-config.sh
#   3. Run: ./scripts/generate-firebase-config.sh
#
# This script generates web/firebase-config.js which is used by:
#   - web/index.html (Firebase initialization)
#   - web/firebase-messaging-sw.js (Service worker)

set -e

# Change to the client directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$CLIENT_DIR"

# Load .env.local if it exists
if [ -f .env.local ]; then
  echo "Loading .env.local..."
  set -a
  source .env.local
  set +a
else
  echo "Warning: .env.local not found. Make sure environment variables are set."
fi

# Check required variables
if [ -z "$FIREBASE_API_KEY" ]; then
  echo "Error: FIREBASE_API_KEY is not set"
  echo "Please create .env.local with your Firebase configuration"
  echo "See .env.example for required variables"
  exit 1
fi

if [ -z "$FIREBASE_VAPID_KEY" ]; then
  echo "Warning: FIREBASE_VAPID_KEY is not set. Web push notifications may not work."
fi

# Generate firebase-config.js for web
cat > web/firebase-config.js << EOF
// Auto-generated Firebase configuration
// DO NOT COMMIT THIS FILE - it contains sensitive API keys
// Generated by: scripts/generate-firebase-config.sh

const firebaseConfig = {
  apiKey: "${FIREBASE_API_KEY}",
  authDomain: "${FIREBASE_AUTH_DOMAIN:-}",
  projectId: "${FIREBASE_PROJECT_ID}",
  storageBucket: "${FIREBASE_STORAGE_BUCKET:-}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${FIREBASE_APP_ID}",
};
EOF

echo "Generated web/firebase-config.js"

# Output build command reminder
echo ""
echo "=== Build Instructions ==="
echo "To build with VAPID key support for web push, run:"
echo ""
echo "  source .env.local"
echo "  flutter build web --release --dart-define=FIREBASE_VAPID_KEY=\$FIREBASE_VAPID_KEY"
echo ""
echo "After building, copy the generated config to the build output:"
echo "  cp web/firebase-config.js build/web/"
echo ""
